// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bolnica_webapi.Data;

#nullable disable

namespace bolnica_webapi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("bolnica_webapi.Odjel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojPacijenata")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Odjeli");
                });

            modelBuilder.Entity("bolnica_webapi.Pacijent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktivan")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatumRodenja")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OdjelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OdjelId");

                    b.ToTable("Pacijenti");
                });

            modelBuilder.Entity("bolnica_webapi.Pacijent", b =>
                {
                    b.HasOne("bolnica_webapi.Odjel", "Odjel")
                        .WithMany("Pacijenti")
                        .HasForeignKey("OdjelId");

                    b.Navigation("Odjel");
                });

            modelBuilder.Entity("bolnica_webapi.Odjel", b =>
                {
                    b.Navigation("Pacijenti");
                });
#pragma warning restore 612, 618
        }
    }
}
